# Generated by Django 5.1.1 on 2024-09-15 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_class_teacher_class_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.class'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, related_name='assigned_teachers', to='core.class'),
        ),
    ]
