# Generated by Django 5.1.1 on 2024-09-15 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_studentclassassignment_teacherclassassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentclassassignment',
            old_name='class_assigned',
            new_name='student_class',
        ),
        migrations.AlterUniqueTogether(
            name='studentclassassignment',
            unique_together={('student', 'student_class')},
        ),
    ]
