# Generated by Django 5.1.1 on 2024-09-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_class_assigned_studentclassassignment_student_class_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentclassassignment',
            unique_together=set(),
        ),
    ]
