# Generated by Django 5.1.1 on 2024-09-16 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_studentclassassignment_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='behavior',
            name='user',
        ),
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
