# Generated by Django 5.1.1 on 2024-09-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bloginfo_attendance_user_behavior_user_note_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='absences',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='presences',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('user',)},
        ),
    ]
