# Generated by Django 5.1.1 on 2024-09-19 16:46

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_payment_class_assigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='behavior',
            old_name='description',
            new_name='commentaire',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='subject',
            new_name='epreuve',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='grade',
            new_name='note',
        ),
        migrations.AddField(
            model_name='behavior',
            name='periode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='date_epreuve',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='behavior',
            name='level',
            field=models.CharField(choices=[('bad', 'Mauvais'), ('average', 'Moyen'), ('good', 'Bon')], max_length=10),
        ),
        migrations.CreateModel(
            name='AutresFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=100)),
                ('date_frais', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
