# Generated by Django 5.1.1 on 2024-09-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_contact_preinscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('device', models.CharField(max_length=30)),
                ('transaction_id', models.CharField(max_length=30)),
                ('transaction_number', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=400)),
            ],
        ),
    ]
